import { Inter } from 'next/font/google'
import DefaultLayout from '@/app/LayoutProvider'
import '@/app/css/satoshi.css'
import '@/app/css/style.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className='dark:bg-boxdark-2 dark:text-bodydark'>
				<DefaultLayout>{children}</DefaultLayout>
			</body>
		</html>
	)
}
